### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by jacebrowning** [tjwalch/django-livereload-server#24]
`livereload` is crashing for me with the new release (0.3.0):

```
Traceback (most recent call last):
   File "manage.py", line 12, in <module>
     execute_from_command_line(sys.argv)
   File "/Users/Browning/Documents/memecomplete/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
     utility.execute()
   File "/Users/Browning/Documents/memecomplete/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/Users/Browning/Documents/memecomplete/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
     self.execute(*args, **cmd_options)
   File "/Users/Browning/Documents/memecomplete/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
     output = self.handle(*args, **options)
   File "/Users/Browning/Documents/memecomplete/.venv/lib/python3.6/site-packages/livereload/management/commands/livereload.py", line 59, in handle
     server.watch(dir)
   File "/Users/Browning/Documents/memecomplete/.venv/lib/python3.6/site-packages/livereload/server.py", line 120, in watch
     self.watcher.watch(filepath, func, delay)
   File "/Users/Browning/Documents/memecomplete/.venv/lib/python3.6/site-packages/livereload/watcher.py", line 53, in watch
     'ignore': ignore,
 TypeError: unhashable type: 'list'
```

I do not experience this issue with 0.2.3.

**Comment by tjwalch** [comment]
Looks like I have to be more careful when merging contributed PR's. Fix is coming up!

**Comment by tjwalch** [comment]
Works for me now in 0.3.1
