### ISSUE TITLE
Exception in callback - TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by derekkinzo** [tjwalch/django-livereload-server#54]
```
[E 210824 12:02:32 ioloop:907] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "...\lib\site-packages\tornado\ioloop.py", line 905, in _run
        return self.callback()
      File "...\lib\site-packages\livereload\handlers.py", line 66, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "...\lib\site-packages\livereload\watcher.py", line 71, in examine
        if self.is_changed(path, item['ignore']):
      File "...\lib\site-packages\livereload\watcher.py", line 91, in is_changed
        return self.is_glob_changed(path, ignore)
      File "...\lib\site-packages\livereload\watcher.py", line 135, in is_glob_changed
        for f in glob.glob(path):
      File "...\lib\glob.py", line 22, in glob
        return list(iglob(pathname, recursive=recursive))
      File "...\lib\glob.py", line 44, in _iglob
        if not has_magic(pathname):
      File "...\lib\glob.py", line 156, in has_magic
        match = magic_check.search(s)
    TypeError: expected string or bytes-like object
```

**Comment by hndr91** [comment]
did you create a templates and static directory in project root directory?

**Comment by imak-h** [comment]
I have the same issue ! and my static directory is at the same level as manage.py

**Comment by imak-h** [comment]
I have resolve this error by adding a templates folder where manage.py was.
thanks hndr91
